### ISSUE TITLE
Quokka don't work with vite+react+typescript (show ""viteNodeServer.fetchPromiseMap.clear is not a function"" error message)

### ISSUE THREAD

**Issue by v-v-belikov** [wallabyjs/quokka#922]
### Issue description or question

I want to use quokka.js in a project that uses react and typescript and builds using vite. I configured everything as indicated in the documentation:
- For React, installed “jsdom”, indicated in the config that “jsdom-quokka-plugin” is used, and indicated in index.tsx that it is used in the test environment.
- Just in case, I installed “ts-node” and “tsconfig-paths”. "typescript" was already installed.
- Installed "vite-node"

When activating an extension in a file, quokka displays the message "viteNodeServer.fetchPromiseMap.clear is not a function" in the output window.

Please help me solve the problem. I bought quokka.js as a gift for my younger Brother. He is studying to become a frontend developer and is developing a project, the link to the repository of which is given below. I am sure that your extension will help him understand the code faster and learn more successfully. But it's very sad that it doesn't work in this case.

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

Yes

Yes

### Sample repository link

https://github.com/v-v-belikov/quokka-configuration

### Quokka.js Console Output

```
viteNodeServer.fetchPromiseMap.clear is not a function 
```

### Code editor version

Visual Studio Code v1.85.1

### OS name and version

Windows 10

**Comment by helmuthdu** [comment]
Same issue, it starts happening after upgrading to Vitest v1.x.x. Downgrade to v0.34.7 temporary fix the issue.

**Comment by smcenlly** [comment]
Thanks for reporting the issue, and for describing the temporary fix. We have added support for `vite-node@v1.x+` in the latest version of Quokka. 

Please update to Quokka for VS Code `v1.0.604+`; it will fix your problem.
